export enum ApiErrorCode {
  InvalidUrl = 'INVALID_URL',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  InvalidAuthToken = 'INVALID_AUTH_TOKEN',
  InvalidEmail = 'INVALID_EMAIL',
  EmailMismatch = 'EMAIL_MISMATCH',
  AccountAlreadyLinked = 'ACCOUNT_ALREADY_LINKED',
  NotAdmin = 'NOT_ADMIN',
  NoAdminUser = 'NO_ADMIN_USER',
  ConnectionError = 'CONNECTION_ERROR',
  SyncErrorGroupedFolders = 'SYNC_ERROR_GROUPED_FOLDERS',
  SyncErrorNoLibraries = 'SYNC_ERROR_NO_LIBRARIES',
  Unauthorized = 'UNAUTHORIZED',
  Unknown = 'UNKNOWN',
}
